### ISSUE TITLE
Project copyright?

### ISSUE THREAD

**Issue by wleepang** [pytest-dev/iniconfig#26]
Hello, I'm using this package in my project and am curious if there is a copyright notice I should reference for it for attribution. The license file does not have a specific copyright notice.

**Comment by rparini** [comment]
In addition, the current MIT license does not make sense without a copyright notice as it mentions
> The above copyright notice

which does not exist.

**Comment by RonnyPfannschmidt** [comment]
the license is added in the license file and the source refers to it

**Comment by rparini** [comment]
@RonnyPfannschmidt The license file does exist but it does not include a copyright notice. For example, the [pytest LICENSE file](https://github.com/pytest-dev/pytest/blob/cab02e67d7e2c657527b41e76a00a594a8d99806/LICENSE#L3) has
```
Copyright (c) 2004 Holger Krekel and others
```
but there is no similar copyright notice in the [LICENSE file](https://github.com/pytest-dev/iniconfig/blob/6bc5528789498c360577770cbb4bb779134ffce1/LICENSE) in this repository. 

A copyright notice is needed because the MIT license this repository uses says 
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.
